### ISSUE TITLE
Split bundle bugs

### ISSUE THREAD

**Issue by jamestalmage** [avajs/karma-ava#1]
Browserifies `b.external(ext)` method suffers from a few issues when `ext` is another bundle.
1. You must call `b2.external(b1)` before you call `b1.bundle` (https://github.com/substack/node-browserify/pull/1577). This makes it pretty useless for bundle splitting for `karma-ava`. The idea is to bundle `ava` once as an external to avoid the expense of bundling it for every single test. 
2. It's just buggy (https://github.com/substack/node-browserify/pull/1583)

`lib/externalize-bundle.js` pulls it's implementation directly from the browserify source. It solves `1`, but `2` remains an issue.

**Comment by sindresorhus** [comment]
Have you considered using `webpack`?

**Comment by jamestalmage** [comment]
Yes. IMO, that is still on the table. It does allow split bundles, however, from what I can tell, the split needs to be defined up front. We can't just bundle AVA once, then add additional bundles dynamically that exclude everything in the first bundle. I haven't explored deeply enough to confirm, but I think that is the case.

Ideally AVA would have mechanisms for browser testing across a range of bundlers.
